server.host: "0.0.0.0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
server.maxPayload: 10485760 # Set to 10MB
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "d7a9g1b3c5e8f2h4j6k8m0p2q4s6u8w0"
xpack.reporting.encryptionKey: "f1g3h5j7k9m2n4p6q8r0t2v4x6z8b0d2"
xpack.security.encryptionKey: "a1c3e5g7i9k2m4o6q8s0u2w4y6a8c0e2"
